#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create

spring:
  datasource:
    url: ${DATABASE_URL} # Usa a variável fornecida pelo Railway
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # Ajuste conforme necessário
  sql:
    init:
      mode: always